### ISSUE TITLE
Update donor & microsponsor shortcodes

### ISSUE THREAD

**Issue by joedolson** [wpa11yday/conference#29]
Currently, donor and microsponsors are pulled directly from the Gravity Forms data. This is messy and convoluted.

Donor & microsponsor forms should be updated so that they feed into the people/sponsor post types so we can pull that data more elegantly.

- [x] Forms create donor/sponsor records if the donor checks the 'share my information' options.
- [x] Test data added
- [x] Shortcodes updated

Let's not fix this in the 2022 archive; no reason to migrate all that data, we can just retain the code to generate and create new versions for next year.

Once those forms are updated and we have data, we can update the shortcodes.

@amberhinds First step is on you, I think!

**Comment by joedolson** [comment]
I've eliminated the custom shortcodes from the plugin & rebuilt the sponsors shortcode to be able to limit to display specific levels.

**Comment by amberhinds** [comment]
Thanks

**Comment by joedolson** [comment]
Pretty sure this is all done; closing.
