### ISSUE TITLE
Implement code linting

### ISSUE THREAD

**Issue by joedolson** [wpa11yday/conference#3]
Implement code linting and clean up errors.

**Comment by NicktheGeek** [comment]
@joedolson are there any specific linting guidelines? I have a good bit of experience setting this up and can take responsibility for this issue.

**Comment by joedolson** [comment]
Sorry; I was already setting this up when I saw this. I'm only setting up PHP linting, however, using the core WPCS styles. There's going to be a lot of work to do to fix all the errors though - the plugin we forked for this was not up to those standards.

If you can work on JS linting, that would be great; I don't have any experience setting that up.

**Comment by NicktheGeek** [comment]
JS Linting is complete.
