### ISSUE TITLE
Customizer doesn't load

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/conference#33]
**Describe the bug**
The customizer doesn't load on the website. There is a repeating debug warning "Warning: Attempt to read property "post_type" on null in /home/wp/www/2023/wp-content/plugins/wpad-conference-schedule/wp-conference-schedule.php on line 391
" That may be unrelated but I'm not sure, so I'm opening the issue on the plugin just in case.

Nothing in the console.

There is a browser alert that just says, "cannot load media". 

**To Reproduce**
1. Open the customizer on the 2023 site on any page.

**Expected behavior**
The customizer will work.

**Screenshots**
<img width="1705" alt="Screen Shot of browser alert and debug warning" src="https://user-images.githubusercontent.com/13153456/229673534-6a1e7e14-7b9d-49db-9529-3e606a97dc17.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

**Comment by amberhinds** [comment]
I do question whether this is a theme issue...

**Comment by joedolson** [comment]
No longer occurring; probably fixed in the PHPCS clean up.
