### ISSUE TITLE
Add posts written by the person on their public profile if posts exist and redirect author links

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/conference#36]
To avoid duplication, we're using the people post type as the author page and listing posts by that author on the page.  You can see an [example of this on my profile on the 2022 site](https://2022.wpaccessibility.day/people/amber-hinds/). This is currently being accomplished manually:

- The heading is added into the bio followed by a Display Posts shortcode to list the posts by that author.
- A redirect is created from the author archive to the person's profile.

A possible enhancement to the plugin might be to handle this automatically. It's not emergent by any means, but it could be nice not to have to set this up manually for every author.

**Comment by joedolson** [comment]
We'll need to add some kind of additional data on the profile that can connect the people post type to their user - user ID or email would be easiest.  This will really only apply to organizers - and we don't really have an organizer onboarding form, so we'll have to do that manually. If we're really consistent in structuring usernames, we could do it just from name - but we haven't been doing things that way to date. 

Thoughts?

**Comment by amberhinds** [comment]
A meta field to select the user is probably fine.

**Comment by amberhinds** [comment]
@joedolson I'm adding an organizer onboarding form now and will add the user email address in a meta field on the user post type. I'm going to save the data as wpcsp_user_email.
