### ISSUE TITLE
Add "approved" post status

### ISSUE THREAD

**Issue by NicktheGeek** [wpa11yday/conference#40]
**Is your feature request related to a problem? Please describe.**
The current post type approval work flow includes draft and pending review, but no way to indicate the content has been reviewed and approved.

**Describe the solution you'd like**
We can add and "Approved" post status to all post types.

**Describe alternatives you've considered**
It was discussed to potentially use draft or pending depending on how the content is created, but this could lead to confusion.

**Comment by joedolson** [comment]
One of the things that's a key benefit to an 'Approved' status is that pending and draft statuses can be automatically assigned (onboarding forms, etc.), but approved should always require somebody to actually review the content; this gives us a clearer pathway in pre-publication.

**Comment by amberhinds** [comment]
@NicktheGeek @joedolson - any chance we can get this tomorrow? I'm working on the instructions for the content team so they can start editing posts.

**Comment by NicktheGeek** [comment]
@amberhinds working on it now :)

**Comment by amberhinds** [comment]
Thank you!!
