### ISSUE TITLE
Need the ability to define the image sized being used by the wpcs_speakers shortcode

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/conference#43]
Some of the images on the [organizers page](https://staging.wpaccessibility.day/about/organizers/) are slightly taller or shorter because it's not using a hard cropped image. 

I would be happy with either of these solutions:

1. Add an attribute to the wpcs_speakers shortcode to be able to choose the image size being used.
2. Just hard code that shortcode to use the large-square size defined in the theme.

**Comment by joedolson** [comment]
This was fixed a few days ago in https://github.com/wpa11yday/conference/commit/d7bc8ec9a266080a27d19a0e5933d79260f08feb
