### ISSUE TITLE
Facebook URL field missing from Edit Sponsor page

### ISSUE THREAD

**Issue by peteringersoll** [wpa11yday/conference#58]
After fixing the Twitter URL field that missing from the Edit Sponsor page, it now looks like Facebook URL is missing.

![WPAD-FB-issue](https://github.com/wpa11yday/conference/assets/34354546/649b354b-1c34-48e9-8622-b99d5ecdc307)

**Comment by joedolson** [comment]
In https://github.com/wpa11yday/conference/commit/e9adcbe0b1d5ee7dba096e161e64411648d984dd
