### ISSUE TITLE
Attendees Twitter logo should be updated to X

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/conference#68]
https://2024.wpaccessibility.day/about/attendees/

These still use the bird logo. It would be good to update to the X.

**Comment by joedolson** [comment]
Also the social media header items.

**Comment by amberhinds** [comment]
I should be able to do the nav menus. Those are not coded in the theme.

**Comment by joedolson** [comment]
I also updated the nav menus at the same time in both the template and 2024. Left the archive sites, though.
