### ISSUE TITLE
Add a Twitter handles meta field to the posts post type

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/conference#71]
I would like a single line text field added to the posts post type called "X Handles to Tag" with this helper text: 

Add Twitter/X handles including the @ symbol that you would like to tag when this post gets published. For example: @WPA11yDay. If you are adding multiple, separate with commas or include the word "and" as you would if writing them in a Tweet.

This doesn't need to be output on the front end - I just need to know the key so I can reference it with the WP to Buffer plugin.

**Comment by joedolson** [comment]
Closed in https://github.com/wpa11yday/conference/commit/00108888a5760da247599372e3eca842e32e078d
